// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/job-details/:id": {
    params: {
      "id": string;
    };
  };
  "/permissions": {
    params: {};
  };
  "/permissions/:id": {
    params: {
      "id": string;
    };
  };
  "/automation": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/execution": {
    params: {};
  };
  "/scheduled": {
    params: {};
  };
  "/scheduled/create": {
    params: {};
  };
  "/scheduled/:id": {
    params: {
      "id": string;
    };
  };
  "/machines": {
    params: {};
  };
  "/packages": {
    params: {};
  };
  "/packages/upload": {
    params: {};
  };
  "/machine": {
    params: {};
  };
  "/machine/create": {
    params: {};
  };
  "/machine/:id": {
    params: {
      "id": string;
    };
  };
  "/project": {
    params: {};
  };
  "/project/:id": {
    params: {
      "id": string;
    };
  };
  "/assets": {
    params: {};
  };
  "/assets/create": {
    params: {};
  };
  "/assets/:id": {
    params: {
      "id": string;
    };
  };
  "/queues": {
    params: {};
  };
  "/roles": {
    params: {};
  };
  "/users": {
    params: {};
  };
  "/users/create": {
    params: {};
  };
  "/users/:id": {
    params: {
      "id": string;
    };
  };
  "/jobs": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/job-details/:id" | "/permissions" | "/permissions/:id" | "/automation" | "/dashboard" | "/execution" | "/scheduled" | "/scheduled/create" | "/scheduled/:id" | "/machines" | "/packages" | "/packages/upload" | "/machine" | "/machine/create" | "/machine/:id" | "/project" | "/project/:id" | "/assets" | "/assets/create" | "/assets/:id" | "/queues" | "/roles" | "/users" | "/users/create" | "/users/:id" | "/jobs" | "/login" | "/*";
  };
  "routes/_layout.tsx": {
    id: "routes/_layout";
    page: "/job-details/:id" | "/permissions" | "/permissions/:id" | "/automation" | "/dashboard" | "/execution" | "/scheduled" | "/scheduled/create" | "/scheduled/:id" | "/machines" | "/packages" | "/packages/upload" | "/machine" | "/machine/create" | "/machine/:id" | "/project" | "/project/:id" | "/assets" | "/assets/create" | "/assets/:id" | "/queues" | "/roles" | "/users" | "/users/create" | "/users/:id" | "/jobs";
  };
  "routes/_layout.job-details.$id.tsx": {
    id: "routes/_layout.job-details.$id";
    page: "/job-details/:id";
  };
  "routes/_layout.permissions.tsx": {
    id: "routes/_layout.permissions";
    page: "/permissions" | "/permissions/:id";
  };
  "routes/_layout.permissions.$id.tsx": {
    id: "routes/_layout.permissions.$id";
    page: "/permissions/:id";
  };
  "routes/_layout.automation.tsx": {
    id: "routes/_layout.automation";
    page: "/automation";
  };
  "routes/_layout.dashboard.tsx": {
    id: "routes/_layout.dashboard";
    page: "/dashboard";
  };
  "routes/_layout.execution.tsx": {
    id: "routes/_layout.execution";
    page: "/execution";
  };
  "routes/_layout.scheduled.tsx": {
    id: "routes/_layout.scheduled";
    page: "/scheduled" | "/scheduled/create" | "/scheduled/:id";
  };
  "routes/_layout.scheduled.create.tsx": {
    id: "routes/_layout.scheduled.create";
    page: "/scheduled/create";
  };
  "routes/_layout.scheduled._index.tsx": {
    id: "routes/_layout.scheduled._index";
    page: "/scheduled";
  };
  "routes/_layout.scheduled.$id.tsx": {
    id: "routes/_layout.scheduled.$id";
    page: "/scheduled/:id";
  };
  "routes/_layout.machines.tsx": {
    id: "routes/_layout.machines";
    page: "/machines";
  };
  "routes/_layout.packages.tsx": {
    id: "routes/_layout.packages";
    page: "/packages" | "/packages/upload";
  };
  "routes/_layout.packages.upload.tsx": {
    id: "routes/_layout.packages.upload";
    page: "/packages/upload";
  };
  "routes/_layout.packages._index.tsx": {
    id: "routes/_layout.packages._index";
    page: "/packages";
  };
  "routes/_layout.machine.tsx": {
    id: "routes/_layout.machine";
    page: "/machine" | "/machine/create" | "/machine/:id";
  };
  "routes/_layout.machine.create.tsx": {
    id: "routes/_layout.machine.create";
    page: "/machine/create";
  };
  "routes/_layout.machine.$id.tsx": {
    id: "routes/_layout.machine.$id";
    page: "/machine/:id";
  };
  "routes/_layout.project.tsx": {
    id: "routes/_layout.project";
    page: "/project" | "/project/:id";
  };
  "routes/_layout.project.$id.tsx": {
    id: "routes/_layout.project.$id";
    page: "/project/:id";
  };
  "routes/_layout.assets.tsx": {
    id: "routes/_layout.assets";
    page: "/assets" | "/assets/create" | "/assets/:id";
  };
  "routes/_layout.assets.create.tsx": {
    id: "routes/_layout.assets.create";
    page: "/assets/create";
  };
  "routes/_layout.assets._index.tsx": {
    id: "routes/_layout.assets._index";
    page: "/assets";
  };
  "routes/_layout.assets.$id.tsx": {
    id: "routes/_layout.assets.$id";
    page: "/assets/:id";
  };
  "routes/_layout.queues.tsx": {
    id: "routes/_layout.queues";
    page: "/queues";
  };
  "routes/_layout.roles.tsx": {
    id: "routes/_layout.roles";
    page: "/roles";
  };
  "routes/_layout.users.tsx": {
    id: "routes/_layout.users";
    page: "/users" | "/users/create" | "/users/:id";
  };
  "routes/_layout.users.create.tsx": {
    id: "routes/_layout.users.create";
    page: "/users/create";
  };
  "routes/_layout.users._index.tsx": {
    id: "routes/_layout.users._index";
    page: "/users";
  };
  "routes/_layout.users.$id.tsx": {
    id: "routes/_layout.users.$id";
    page: "/users/:id";
  };
  "routes/_layout.jobs.tsx": {
    id: "routes/_layout.jobs";
    page: "/jobs";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_layout": typeof import("./app/routes/_layout.tsx");
  "routes/_layout.job-details.$id": typeof import("./app/routes/_layout.job-details.$id.tsx");
  "routes/_layout.permissions": typeof import("./app/routes/_layout.permissions.tsx");
  "routes/_layout.permissions.$id": typeof import("./app/routes/_layout.permissions.$id.tsx");
  "routes/_layout.automation": typeof import("./app/routes/_layout.automation.tsx");
  "routes/_layout.dashboard": typeof import("./app/routes/_layout.dashboard.tsx");
  "routes/_layout.execution": typeof import("./app/routes/_layout.execution.tsx");
  "routes/_layout.scheduled": typeof import("./app/routes/_layout.scheduled.tsx");
  "routes/_layout.scheduled.create": typeof import("./app/routes/_layout.scheduled.create.tsx");
  "routes/_layout.scheduled._index": typeof import("./app/routes/_layout.scheduled._index.tsx");
  "routes/_layout.scheduled.$id": typeof import("./app/routes/_layout.scheduled.$id.tsx");
  "routes/_layout.machines": typeof import("./app/routes/_layout.machines.tsx");
  "routes/_layout.packages": typeof import("./app/routes/_layout.packages.tsx");
  "routes/_layout.packages.upload": typeof import("./app/routes/_layout.packages.upload.tsx");
  "routes/_layout.packages._index": typeof import("./app/routes/_layout.packages._index.tsx");
  "routes/_layout.machine": typeof import("./app/routes/_layout.machine.tsx");
  "routes/_layout.machine.create": typeof import("./app/routes/_layout.machine.create.tsx");
  "routes/_layout.machine.$id": typeof import("./app/routes/_layout.machine.$id.tsx");
  "routes/_layout.project": typeof import("./app/routes/_layout.project.tsx");
  "routes/_layout.project.$id": typeof import("./app/routes/_layout.project.$id.tsx");
  "routes/_layout.assets": typeof import("./app/routes/_layout.assets.tsx");
  "routes/_layout.assets.create": typeof import("./app/routes/_layout.assets.create.tsx");
  "routes/_layout.assets._index": typeof import("./app/routes/_layout.assets._index.tsx");
  "routes/_layout.assets.$id": typeof import("./app/routes/_layout.assets.$id.tsx");
  "routes/_layout.queues": typeof import("./app/routes/_layout.queues.tsx");
  "routes/_layout.roles": typeof import("./app/routes/_layout.roles.tsx");
  "routes/_layout.users": typeof import("./app/routes/_layout.users.tsx");
  "routes/_layout.users.create": typeof import("./app/routes/_layout.users.create.tsx");
  "routes/_layout.users._index": typeof import("./app/routes/_layout.users._index.tsx");
  "routes/_layout.users.$id": typeof import("./app/routes/_layout.users.$id.tsx");
  "routes/_layout.jobs": typeof import("./app/routes/_layout.jobs.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/$": typeof import("./app/routes/$.tsx");
};